### ISSUE TITLE
how can I install a newer version?

### ISSUE THREAD

**Issue by levidrain** [nikku/hugo-cli#14]
How can I request a newer version of hugo?

**Comment by Logikgate** [comment]
@levidrain you can use a newer version of hugo by setting the environment variable to the version you want prior to running hugo-cli.  

`HUGO_VERSION=0.24.1 node hugo`

Note: the current version of hugo-cli does not work with hugo versions later than 0.20.3, you can reference pull request #15 for more info on that

**Comment by nikku** [comment]
After merging #15, this should now be possible. 

Fixed in `hugo-cli@0.5.1`.
