### ISSUE TITLE
fresh install run error events.js:160

### ISSUE THREAD

**Issue by sugizo** [nikku/hugo-cli#16]
already tried to install on another directory, restart the computer but still met an error, here the environment and step i took
$ node -v
v6.11.2
$ npm -v
3.10.10
$ cd ~/hugo
$ npm install hugo-cli
$ node_modules/.bin/hugo -h
hugo not downloaded yet. attempting to grab it...
fetched hugo v0.30.2
extracting archive...
we got it, let's go!

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/sugizo/hugo/node_modules/hugo-cli/tmp/hugo_0.30.2_darwin_amd64 ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by nikku** [comment]
I've updated the CLI to include debug output. 

Could you use `hugo-cli@0.5.3` and run your command with the `--verbose` flag?

**Comment by nikku** [comment]
(seems like extracting Hugo does not work correctly on MacOS).

**Comment by sugizo** [comment]
$ npm install hugo-cli@0.5.3

$ node_modules/.bin/hugo --verbose
DEBUG target={ platform: 'darwin', arch: 'x64' }
DEBUG searching executable at </Users/sugizo/hugo/node_modules/hugo-cli/tmp/hugo_0.30.2_darwin_amd64>
hugo not downloaded yet. attempting to grab it...
DEBUG downloading archive from <https://github.com/spf13/hugo/releases/download/v0.30.2/hugo_0.30.2_macOS-64bit.zip>
fetched hugo v0.30.2
extracting archive...
DEBUG extracted archive to </Users/sugizo/hugo/node_modules/hugo-cli/tmp>
executable </Users/sugizo/hugo/node_modules/hugo-cli/tmp/hugo_0.30.2_darwin_amd64> not found
please report this as a bug
(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: executable not found

$ ls -la node_modules/hugo-cli/tmp/hugo_0.30.2_macOS-64bit.zip 
-rw-r--r--  1 sugizo  staff  129195 Oct 27 21:43 node_modules/hugo-cli/tmp/hugo_0.30.2_macOS-64bit.zip

**Comment by nikku** [comment]
Thanks for the info. What is the content of the `node_modules/hugo-cli/tmp/` folder?

**Comment by sugizo** [comment]
node_modules/hugo-cli/tmp have only 1 file :
hugo_0.30.2_macOS-64bit.zip 

trying to extract it manually via gui finder (hugo_0.30.2_macOS-64bit.zip) and got the result is file : hugo_0.30.2_macOS-64bit.zip.cpgz

**Comment by nikku** [comment]
Thanks for your input. Should be fixed with `hugo-cli@0.5.4`.

**Comment by nikku** [comment]
Adressed via https://github.com/nikku/hugo-cli/commit/767780ce9dba6e86f33755cb7bbbfbb0992563fa.
