### ISSUE TITLE
Hugo >= 0.54.0 not be able to download

### ISSUE THREAD

**Issue by Legiew** [nikku/hugo-cli#24]
Hey,

since hugo 0.54.0 they changed the download link in github. So it is not possible to use hugo-cli for this version. Is it possible to use the current version with a flag or setting or do we need an updated version of the cli?

0.54.0: github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_macOS-64bit.tar.gz
0.53.0: github.com/gohugoio/hugo/releases/download/v0.53/hugo_extended_0.53_macOS-64bit.tar.gz

**Comment by nikku** [comment]
We'd need to introduce a switch to handle the versions starting at `0.54` differently.

Happy to take a PR that improves this (and [adds the relevant test coverage](https://github.com/nikku/hugo-cli/blob/master/test/integration.js#L14)).

**Comment by Legiew** [comment]
Okay I will have a look at the next days. Seems like we have to skip the trimming of the version string if the version is >= 0.54.0. Shouldn't be impossible :-)

**Comment by Legiew** [comment]
Was easier than expected: #25

**Comment by nikku** [comment]
Fixed via https://github.com/nikku/hugo-cli/pull/25.

**Comment by nikku** [comment]
Released as `v0.10.0`.
