### ISSUE TITLE
Add example on how to download specific hugo version

### ISSUE THREAD

**Issue by ibnumalik** [nikku/hugo-cli#31]
Hi, thanks for creating this cli. I have a suggestion to add example to README file on how to download specific hugo version.

```bash
$ HUGO_VERSION=0.64.0 npx hugo version
```

**Comment by nikku** [comment]
Your contribution (a PR) is appreciated!

**Comment by ibnumalik** [comment]
I've open a PR for this. #32 Please review it.

**Comment by nikku** [comment]
Thanks for your contribution.

Closed via https://github.com/nikku/hugo-cli/pull/32.
