### ISSUE TITLE
How to run with specific version in grunt?

### ISSUE THREAD

**Issue by bluecaret** [nikku/hugo-cli#33]
Hello, I'm trying to setup hugo-cli to use a specific version (the latest extended version) via a grunt-exec script but any time I do that I get an error:

```
>> 'HUGO_VERSION' is not recognized as an internal or external command,
>> operable program or batch file.
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: HUGO_VERSION=extended_0.64.0 npx hugo-cli
>> 'HUGO_VERSION' is not recognized as an internal or external command,
>> operable program or batch file.
```

I think I have found that if I run it like this in a standard command prompt (via the below commands) it works, but I am unable to get this to work via grunt no matter the combinations I try.

```
> set HUGO_VERSION=extended_0.64.0
> npx hugo-cli
```

This is a windows machine.

Thanks!

**Comment by nikku** [comment]
Please learn how to pass environment variables to the script you execute via grunt.

```
FOO=1 some-cmd
```

does not work on Windows. You could use [cross-env](npmjs.com/package/cross-env) to make things compatible.

**Comment by bluecaret** [comment]
Thank you for the quick response. cross-env is exactly what I was needing! 

For anyone else, the link above doesn't work but I found it here: https://github.com/kentcdodds/cross-env
