### ISSUE TITLE
The hugo is not building the assets files (scss, js)

### ISSUE THREAD

**Issue by valterbarros** [nikku/hugo-cli#34]
I'm using hugo 0.75.1 version on ubuntu 20

Using that to run:

```
HUGO_VERSION=0.75.1 node_modules/.bin/hugo serve --environment development
```

I change a scss file and it don't generate the resources file, but if I run the hugo build that is installed on my system it generates

**Comment by nikku** [comment]
Please verify that you use the same Hugo versions:

```
hugo version
HUGO_VERSION=0.75.1 npx hugo-cli version
```

Other than that I have no idea what could be different.

**Comment by valterbarros** [comment]
what is the right executable? hugo or hugo-cli

**Comment by valterbarros** [comment]
![image](https://user-images.githubusercontent.com/17336201/96877242-caa95900-144f-11eb-8cc2-aa54d412b1e1.png)

**Comment by valterbarros** [comment]
on is `v0.75.1-A4A7BAB7` and other `v0.75.1/extended`

**Comment by nikku** [comment]
There you go. You are using the stock hugo version in one place and the HUGO extended version in another place. 

Please refer to [the readme](https://github.com/nikku/hugo-cli/blob/master/README.md#download-specific-hugo-version) to learn how to explicitly fetch extended versions.

I guess that should solve your issue? If not, please provide further details.

**Comment by nikku** [comment]
> what is the right executable? hugo or hugo-cli

It is `hugo-cli` when executed via `npx`.

It is `hugo` when being locally installed and run via a `package.json` script:

```json
{
  ...
  "scripts": {
    "build": "hugo ..."
  },
  "dependencies": {
    "hugo-cli": "*"
  }
}
```

**Comment by valterbarros** [comment]
thanks, man, use extended version solved my problem
