### ISSUE TITLE
> 0.17 download names are in a different format

### ISSUE THREAD

**Issue by paulblyth** [nikku/hugo-cli#7]
When trying to use a specific version of hugo, the download fails (404 - downloads the html) on version 0.17 and above. 

This is because hugo-cli looks for `hugo_${version}_${platform}_${arch}` e.g. `hugo_0.17_darwin_amd64.zip` but the actual filename is `hugo_0.17_MacOS-64bit.zip`

**Comment by nikku** [comment]
I'm happy to take a PR on this one.

**Comment by paulblyth** [comment]
I'll see what I can do. I've noticed that the naming convention changes across other versions (I think 0.16 was different again), so short of maintaining a map I'm not sure how straight forward this will be. I wonder if @spf13 or @bep might be willing to standardise the filenames to make it easier?

**Comment by bep** [comment]
The current file names is the standard and will continue to be like that. We moved away from the platform/arch pattern because it is confusing for some people (Darwin vs macOS etc.) -- and then I guess a semi-manual step made it inconsistent. We have plans to fully automate the release process, but the names will stick.

This is how it is going to be:

https://github.com/spf13/hugo/releases/tag/v0.18.1

**Comment by paulblyth** [comment]
Thanks @bep 

@nikku I'll look at a PR as soon as I get a chance. I'll put in some conditions for the releases we know are different and standardise on the others.

Cheers.

**Comment by paulblyth** [comment]
Actually @nikku are you bothered about supporting < 0.18.1 releases? We could just remove that complexity and support only 0.18.1 and up?

**Comment by bep** [comment]
I know some people cling onto their Hugo 0.17 (some have valid reasons that we will address in Hugo 0.19, i.e. mostly the "index.md hack" that people have been using, that does not work anymore).

**Comment by paulblyth** [comment]
The Hugo 0.17 users can't use hugo-cli anyway because it defaults to 0.15 and the 0.17 release filenames do not match what hugo-cli generates... 

It's the users of Hugo 0.15 and below that will lose support in hugo-cli

**Comment by bep** [comment]
OK, then I would say just drop it. Hugo 0.15 is ancient software by now.

**Comment by paulblyth** [comment]
@bep quick question, are the extracted executable filenames likely to change?

Just looking at 0.18.1 for macOS 64 bit the download filename is `hugo_0.18.1_macOS-64bit.zip` but the executable name is `hugo_0.18.1_darwin_amd64`, so if I'm putting some logic in to accommodate for that it will be hard to maintain if it is going to change.

Thanks

**Comment by bep** [comment]
I haven't thought about that... 

We currently use `gox` to do the builds, and the binary names are out-of-the box. We just have a script that renames the package files afterwords. 

I guess the only reason we still use `gox` is the deb support. But I would say that it is likely that we will move away from `gox`, so ... I'm not sure, my best guess is that the binary names will, at some point, be named like their container zip file etc.

**Comment by nikku** [comment]
Merged for now, we'll adjust the binary names, once there are upstream changes.

**Comment by paulblyth** [comment]
Thanks @nikku - unfortunately I've found that the windows.zip doesn't extract to tmp/binary_folder/binary.exe like the Mac files, so I'll file a bug and PR for that later today
